### ISSUE TITLE
Dockerfile build issue

### ISSUE THREAD

**Issue by kdpsingh** [georgestagg/webR#10]
When building the Dockerfile, I got this error: #7 3.703 E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/binary-arm64/Packages  404  Not Found [IP: 91.189.91.38 80]

This is fixed if you change the Dockerfile to run the apt-get update command first (see below).

May be worth changing the order (see below) unless there's a security/other reason not to do this.

```
RUN apt-get update && \
    echo "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe" >> /etc/apt/sources.list && \
    echo "deb http://security.ubuntu.com/ubuntu/ trusty-security main" >> /etc/apt/sources.list && \
    apt-get -y install --no-install-recommends \
        build-essential curl wget git gnutls-bin bash make cmake ca-certificates xz-utils \
        gfortran-4.6 g++-4.6 gcc-4.6 gcc-4.6-plugin-dev gfortran-4.6 llvm-3.3-dev python3 \
		libbz2-dev liblzma-dev libpcre2-dev libcurl4-openssl-dev libpng-dev clang-3.3 zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*
```

I'm on an M1 Mac, which is likely why this issue occurred.

**Comment by georgestagg** [comment]
I think the `apt-get update` needs to be left after the `echo` commands because they add some extra (very old) repositories to `apt` which are then picked up by the `update`.

I'm not sure what went wrong, but I'll try a clean build with no cache at some point soon and see if I can reproduce.

**Comment by kdpsingh** [comment]
Got it! Thank you for the explanation. Feel free to close this issue.
