### ISSUE TITLE
Which License?

### ISSUE THREAD

**Issue by georgestagg** [georgestagg/webR#16]
I'd like to release this under MIT, as I prefer permissive licenses. However, R is released under the GPL. It could certainly be argued that this entire project is a derivative work and so also required to be released under GPL license. Particularly if we are distributing webR binaries.

Perhaps we could release the infrastructure and build/make scripts under MIT, and the R patches and binary separately under GPL?

Perhaps it would be easier just to license this entire project GPL?

**Comment by lionel-** [comment]
I think releasing the build scripts as MIT and the patches as GPL sounds reasonable. We'll also have a bunch of R code in a webR package that can be released as MIT (we generally use the MIT licence for our packages).

WDYT @hadley?

**Comment by hadley** [comment]
Licensing as much as possible as MIT seems good to me; we'll just need to make it clear to focus that the webR binaries remain GPL.

**Comment by lionel-** [comment]
@georgestagg LGTM

**Comment by hadley** [comment]
Me too
