### ISSUE TITLE
Tidy up R patches

### ISSUE THREAD

**Issue by georgestagg** [georgestagg/webR#2]
Currently the patches just modify the R source directly. This is a quick and easy way to do things for now but isn't great in the long run.

Instead, the preprocessor should be used in the case where there's `ifdef`s already in place, and other code tweaks should be done using `ifdef __EMSCRIPTEN__` or similar.

**Comment by georgestagg** [comment]
The latest R patches are now separated into different files, guarded behind `ifdef`s where possible, and managed using the patch software `quilt`. This is probably as neat and tidy as it's going to get without forking an R repository and managing individual patches with git commits/branches.

We'll try working with `quilt` for a bit. If it becomes difficult or unmanageable I'll revisit this and take another look at how best to organise patches.

**Comment by lionel-** [comment]
Regarding quilt, it looks like stgit (https://stacked-git.github.io/guides/) is worth exploring. This is pretty much quilt but based on git, and it appears from a look at HN discussions that some quilt users have successfully updated their workflow from quilt to stgit.
