### ISSUE TITLE
Is something on iOS blocking the REPL runtime of webR?

### ISSUE THREAD

**Issue by SugarRayLua** [georgestagg/webR#20]
Dear Dr. Stagg,

Thanks for making such great contribution to making R more accessible to everyone! I’m a mobile medical professional and novice programmer and researcher who uses my iPad primarily for my computing at and off-work and have been looking for ways to use R more natively on my iPad. Only one developer that I’m aware of has created an app that runs R natively on the iPad (R Analyst) and that app is now outdated (R 3.1.2), does not allow the user to install packages, has difficult to use GUI, and is not being updated nor working well with the newest iOS version. There are other solutions; the UTM Linux emulator (QEMU port) works very well but needs to be sideloaded to run and is significantly slower running through the emulator than running natively on iPad. The iSH Linux emulator running Alpine Linux doesn’t require emulation but runs R very much slower and frequently is broken. I tried the webR demo and even though it is still in its infancy, I love it! It is a little slow on startup but then is fast executing its commands. The simple split screen of having CLI next to half of a screen that can alternate between displaying R’s file system and plots works great!  Here is a quick time trial experiment I did comparing the different systems running R:

Task: read in a csv data file containing approximately 2.6 million rows and 38 columns into R with read.csv:

Computer          R version.         Time to load 
iMac x86 i5.       4.1.3.                 18 s
webR (iMac).      4.1.3.                 33 s
R analyst (M1 iPad Pro). 3.1.2.    38 s
UTM (M1 iPad Pro) 3.5.2.            4 min, 56 s
ish App (M1 iPad Pro) <version 4 currently broken and unable to test>

Unfortunately, the REPL doesn’t seem to work when I try and run webR in any browser on my iPad (e.g. Safari, Chrome, Firefox). webR starts up okay and lists that it loads up all the R dependencies okay and lets me see the R filesystem fine and import files, but never produces the “>” R command-line prompt. I can tell that webR’s execution is not frozen since I can type on the CLI side of the screen but since there is no command-line prompt it just tells me that there for any R command that I type that there isn’t any such command. Is something on iOS blocking the REPL runtime of webR? If so, hopefully it can be fixed? :-)

PS,
I don’t know if you are familiar with the a-shell app developed by Dr. Holzschuch (https://github.com/holzschu/a-Shell); his app can compile and run wasm files. I’ve communicated with him about my interested in getting R to run natively on the iPad and passed along information about your repository to him. I’m going to see if I can get his a-shell app to run your webR .wasm code.

Fyi.

Have a good upcoming week.

Sincerely,
Mike

**Comment by georgestagg** [comment]
Hi Mike,

I am pleasantly surprised to hear that loading such a CSV works reasonably well in webR. We don’t have much testing in place yet and I’d have guessed it would have just crashed the browser tab!

Safari on iOS used to work and I must have broken it at some point. It looks like the latest build might be working again so I have pushed out an update to the REPL website. You might have to clear the cache on your device to get the latest version of the page. On mine I did Settings -> Safari -> Advanced -> Website data -> swipe and remove ncl.ac.uk data.

To be honest, the interface isn’t the best for mobile. The text is tiny and I think jQuery Terminal might also have one or two bugs there. In any case I’ve attached an image showing what I currently see.

![7C0A7E83-AF23-4E60-8076-798E89BF3660](https://user-images.githubusercontent.com/982548/168495731-91450df6-d7b8-47f4-a56a-1876a5dc0774.jpeg)

**Comment by SugarRayLua** [comment]
Thanks so much, George, it works great now! I’m so excited to see it working on the iPad— I just needed to clear the cache like you said.

I’m happy to troubleshoot/test things on the iPad in my spare time if I can be of help. A couple things I’ve noticed so far:

1. Although the large data file didn’t crash the webR in the iMac it did run it to a problem when I tried to load it on the iPad. webR gave me the following error when I tried to load that large file (that I had uploaded already to webR):

Error: cannot allocate vector of size 15.6 MB

Is that perhaps due to some limitation of the size of the iPad webCache (just guessing, I’m a novice to how web page programming works, too)? I’m still going to try and use your repository to compile R to wasm and run it directly in the a-shell app and see if I get any such limitation. Of note, when read.csv() was able to read in a small csv file fine. 

2. The length of the R screen in the Safari mobile browser is a bit off. If I don’t clear the webR console and keep putting commands in, the console commands go off the bottom of the screen (for which I need to scrolls up the webpage to see but then scrolls back down again when I type input). Anyway in the future to slightly modify the default screen size?

Again, I’m super excited about what you’ve accomplished!

Have a good week,

Mike

**Comment by SugarRayLua** [comment]
@georgestagg,

PS,
Anyway could wire up the View() function in the future to use WebGL instead of X11? Would be great if could pull that off. 

Thanks,
Mike

**Comment by SugarRayLua** [comment]
@georgestagg ,

PPS,
I should have clarified: the length of the screen comment I made above is when using webR on iPad OS on the horizontal position (most common orientation when typing on iOS Keyboard— screenshot below). The size of the font seems fine to me on the iPad.
![IMG_0934](https://user-images.githubusercontent.com/76857619/168672510-cd569e9f-3c8f-4ecb-82ee-6f6b2c3b2fdc.png)

**Comment by SugarRayLua** [comment]
In comparison, this is the R analyst app’s R console on the iPad (way too tiny)
![IMG_0936](https://user-images.githubusercontent.com/76857619/168673984-58c2bf00-e4fd-4c3a-a39b-e1194ba5c9b6.jpeg)
:

**Comment by SugarRayLua** [comment]
Looks like you might even be able to make an x11 like window for webR via web assembly?

https://github.com/ghaerr/microwindows

**Comment by SugarRayLua** [comment]
@georgestagg, I also learned today that there is a “Page Zoom” setting for mobile Safari in settings that could help with the font size issue on the iPhone. Fyi

**Comment by georgestagg** [comment]
Thanks for all the info!

> the console commands go off the bottom of the screen (for which I need to scrolls up the webpage to see but then scrolls back down again when I type input

This will go away once I update the website after some major refactoring we're currently doing. I've fixed the problem but the commit is sitting in a feature branch and hasn't been merged into main yet.

**Comment by SugarRayLua** [comment]
That sounds great! Thanks for letting me know— look forward to it! :-)

**Comment by georgestagg** [comment]
I think compiling R to WASI without the Emscripten toolchain supporting us will be hard, but maybe in the future.

Compiling the `R.bin.wasm` file alone in a-shell will not work: Emscripten's `R.bin.js` sets up the environment and virtual filesystem contents needed to run R. We also have our own support code that sets up input/output around the R REPL by creating methods such as `Module.print` before loading `R.bin.js`. Without that, it's not clear to me how a-shell would know how to get input into the R process and pull output to display.

In https://github.com/holzschu/a-Shell-commands/issues/3, the author briefly discusses the problem of compiling interactive applications for a-shell. The example there is Emacs but the principle is the same. I assume most of the applications in a-shell just deal with input by passing arguments.

**Comment by SugarRayLua** [comment]
Thanks, @georgestagg for your reply. I will pass it along to the a-Shell author.

**Comment by SugarRayLua** [comment]
Thank you, @georgestagg. Have a good rest of your week.
