### ISSUE TITLE
Plotting should support PNG and other bitmap output formats

### ISSUE THREAD

**Issue by georgestagg** [georgestagg/webR#7]
Plotting an image within WASM seems to work okay, at least when using PDF output. The resulting PDF file can be accessed through Emscripten's virtual filesystem via the `FS` object in JS[1].

Bitmap output (e.g. PNG) does not yet work however, due to missing X11. Probably this can be worked around by taking advantage of Emscripten's ports of libraries such as `libpng`. 

Plotting output commands should be modified to work in this environment, or otherwise some other scheme to convert plotting output from PDF to bitmap should be implemented.

----
[1] As an example, attached is a sample image of plotting something directly in the browser using the method above. In this example the resulting PDF is injected into the page via an iFrame.

<img width="500px" alt="Screenshot 2022-01-25 at 13 18 30" src="https://user-images.githubusercontent.com/982548/151011305-7b53d75e-2035-43cd-81df-a4a35b12e5a6.png">

**Comment by georgestagg** [comment]
Whilst not a bitmap, the svglite package has been added to webR ports, which can be used to produce SVG output.

**Comment by psychemedia** [comment]
Can this SVG file be displayed directly (and if so how?) from the `WebR` command line

I note there is a (new to me) [`rsvg`](https://cran.r-project.org/web/packages/rsvg/index.html) package for rendering SVG as bitmaps, but I guess that is blocked by upstream issues relating to bitmap rendering?

I also note that the terminal you seem to be using (https://terminal.jcubic.pl/ ?) supports custom JS functions; noting https://github.com/jcubic/jquery.terminal/issues/278 , could a custom function be defined that will read the contents of the SVG file and display is via an HTML `<svg>` element?

**Comment by jcubic** [comment]
The terminal supports this syntax to render images:

Here is Wiki page that shows how to render images with custom formatters:

https://github.com/jcubic/jquery.terminal/wiki/Formatting-and-Syntax-Highlighting#image-xml-formatter

if you want to use XML-like syntax just include the xml_formattig file.

Here is a demo using this syntax: https://codepen.io/jcubic/pen/poPZGqe?editors=0010

**Comment by jcubic** [comment]
If you want to render SVG probbaly best idea is to jus use raw format:

```javascript
term.echo('<svg ...>', {raw: true});
```

**Comment by georgestagg** [comment]
> Can this SVG file be displayed directly (and if so how?) from the WebR command line?

Not directly, you can use the JS console to get to Emscripten's virtual filesystem though. That's how the screenshot in the initial post worked. It used some JS to talk to the filesystem and grab the file data.

Thanks, Jakub, for the `{raw: true}` tip. In theory I could use that and intercept some special command designed to do exactly as above: grab the SVG data from the virtual FS and echo it to the terminal in raw format. I might add that in the future in any case - However, I've also been working on an alternative that I think is a little better.

R has a concept of creating and registering new graphics devices, and I've modified an existing graphics device designed to output JS code for a HTML canvas so that it works directly within webR. Rather than writing out the JS commands to a file, as originally designed, it just runs them directly in the browser.

I think this is a much more natural way of getting R graphics to work with webR in general and as a bonus we also get working bitmap graphics, since the contents of the resulting HTML canvas element can be downloaded as a `.png` file.

I've updated the webR demo site with the latest version incorporating the new graphics device, so you should be able to give it a go now. You might need to clear your cache to get the latest version of the files. Once you're on the latest version, entering plotting commands into the console should make a plot appear on the right hand side of the screen. Here is how things now look for me:

<img width="1294" alt="Screenshot 2022-02-20 at 18 26 57" src="https://user-images.githubusercontent.com/982548/154858027-4346ffbb-c658-40f9-9dfb-bad9de38729b.png">

**Comment by psychemedia** [comment]
That works really nicely - I was also pleasantly surprised to see that ggplot2 loaded so quickly and rendered a simple chart so easily :-)
