### ISSUE TITLE
Using embedded single quote in string in graphics causes crash/hang.

### ISSUE THREAD

**Issue by barryrowlingson** [georgestagg/webR#71]
Using the amazing: https://webr.gwstagg.co.uk/

```
> plot(1:10)
> title("This is")
```

works fine but then:

`> title("This isn't")`

causes the session to hang with a JS error on the console (latest Firefox, not tried other browsers yet...):

```
Uncaught (in promise) SyntaxError: missing ) after argument list
    <anonymous> repl.ts:180
    async* repl.ts:189
```

First manifest running `demo(graphics)` which makes a pie chart subtitle with a single quote in. System seems find with single quotes embedded in strings for printing etc. Can only make it crash like this when used in a plot...

**Comment by georgestagg** [comment]
Thanks for the report. It's a string escaping issue in the way the HTML canvas graphics device works, which at the moment makes use of nested string interpolation. I'll make some tweaks soon to try and make this a bit smoother in the future, at least for in the case of single quotes.

For the moment, I realise it's not ideal but you can work around it using four extra backslashes to escape the inner string:

```
> plot(1:10)
> title("This isn\\\\'t")
```
