### ISSUE TITLE
New webR terminal has a larger, easier to read font. For those still using older webR, there is an easy way to scale up its font.

### ISSUE THREAD

**Issue by SugarRayLua** [georgestagg/webR#77]
For older version of webR project that uses jquery.terminal all one needs to do is add this css code into the index.html file:

.terminal {
     --size: 1.25;
		}

Where size is the scale compared to the baseline webR terminal that you wish the terminal to display as.

**Comment by lionel-** [comment]
Thank you but please note that Github issues are for bug reports and feature requests. This sort of posts belongs to a user forum such as Community.

**Comment by SugarRayLua** [comment]
Duly noted. Thank you for letting me know.
