### ISSUE TITLE
Easy access to the Emscripten virtual FS should be possible

### ISSUE THREAD

**Issue by georgestagg** [georgestagg/webR#9]
Access to the Emscripten virtual FS should be provided, perhaps via a JS based menu bar and file/directory browser. This would allow for an easy way to upload input data or download vectorised output files such as SVG and PDF.

**Comment by psychemedia** [comment]
It would be really nice to be able to upload sqlite database files into memory at least, and be able to read/write to them in that context.

More complex would be to support the saving and loading of datafiles and scripts into browser storage.

**Comment by georgestagg** [comment]
This can now be handled via the upload/download buttons in the webR REPL app, and the `getFileData` and `putFileData` API on the webR main thread. Documentation is lacking, but I'll make another issue for that.
